version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8000
      - WDS_SOCKET_PORT=3000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    external: true 