version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ganache
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=identity_db
      - BLOCKCHAIN_PROVIDER=http://ganache:8545
    networks:
      - app-network
    volumes:
      - ./backend:/app
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=identity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command: --deterministic --networkId 1337 --chain.vmErrorsOnRPCResponse true
    networks:
      - app-network
    volumes:
      - ganache_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  ganache_data:

networks:
  app-network:
    driver: bridge 